// SPDX-License-Identifier: Apache-2.0
//! Builds the vendored Syphon framework sources (BSD; see vendor/syphon)
//! and the C shim into a static library. macOS only; elsewhere nothing is
//! built.

use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/shim.m");
    println!("cargo:rerun-if-changed=vendor/syphon");
    println!("cargo:rerun-if-env-changed=OM_SYPHON_CHECK_ONLY");
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("macos") {
        return;
    }
    // Type-checking the Rust code from another OS (`cargo check --target
    // aarch64-apple-darwin`), where Apple's compiler is unavailable.
    if env::var_os("OM_SYPHON_CHECK_ONLY").is_some() {
        return;
    }
    if let Err(e) = build() {
        println!("cargo:warning=om-syphon: {e}");
        std::process::exit(1);
    }
}

fn build() -> Result<(), String> {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").map_err(|e| e.to_string())?);
    let out = PathBuf::from(env::var("OUT_DIR").map_err(|e| e.to_string())?);
    let vendor = manifest.join("vendor/syphon");

    // Framework-style includes (`#import <Syphon/X.h>`).
    let headers = out.join("include/Syphon");
    fs::create_dir_all(&headers).map_err(|e| e.to_string())?;
    let mut sources = Vec::new();
    for entry in fs::read_dir(&vendor).map_err(|e| e.to_string())? {
        let path = entry.map_err(|e| e.to_string())?.path();
        match path.extension().and_then(|e| e.to_str()) {
            Some("h") => {
                let name = path.file_name().ok_or("bad header name")?;
                fs::copy(&path, headers.join(name)).map_err(|e| e.to_string())?;
            }
            Some("m" | "c") => sources.push(path),
            _ => {}
        }
    }
    sources.sort();
    shader_header(&vendor, &out)?;

    let mut build = cc::Build::new();
    build
        .files(&sources)
        .file(manifest.join("src/shim.m"))
        .include(out.join("include"))
        .include(&out)
        .include(&vendor)
        .flag("-fobjc-arc")
        .flag("-include")
        .flag(vendor.join("Syphon_Prefix.pch").to_string_lossy().as_ref())
        .define("SYPHON_CORE_SHARE", None)
        .define("GL_SILENCE_DEPRECATION", None)
        // Vendored code: upstream's warnings are not ours to fix.
        .warnings(false)
        .flag("-w");
    build.try_compile("om_syphon").map_err(|e| e.to_string())?;
    for fw in [
        "Foundation",
        "AppKit",
        "Metal",
        "IOSurface",
        "OpenGL",
        "CoreFoundation",
    ] {
        println!("cargo:rustc-link-lib=framework={fw}");
    }
    Ok(())
}

/// Embeds the Metal shaders (with their types header inlined) as a C
/// string, compiled at run time when no framework bundle is present.
fn shader_header(vendor: &Path, out: &Path) -> Result<(), String> {
    let types =
        fs::read_to_string(vendor.join("SyphonServerMetalTypes.h")).map_err(|e| e.to_string())?;
    let shaders =
        fs::read_to_string(vendor.join("SyphonMetalShaders.metal")).map_err(|e| e.to_string())?;
    let source = shaders.replace("#include \"SyphonServerMetalTypes.h\"", &types);
    let mut c = String::from(
        "// Generated by om-syphon/build.rs from SyphonMetalShaders.metal.\nstatic const char kOMSyphonMetalShaderSource[] =\n",
    );
    for line in source.lines() {
        let escaped = line.replace('\\', "\\\\").replace('"', "\\\"");
        c.push_str(&format!("    \"{escaped}\\n\"\n"));
    }
    c.push_str(";\n");
    fs::write(out.join("SyphonMetalShadersSource.h"), c).map_err(|e| e.to_string())
}
